FROM node:18-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY
RUN NEXT_DISABLE_LINTING=1 npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]